name: itinndata
description: A sample command-line application
dependencies:
  browser: any
  lawndart_ext:
    git: git://github.com/orucrob/lawndart_ext.git
  logging: any
  observe: any
dev_dependencies:
  unittest: any
